version: '3.5'
services:
  boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform:
    container_name: boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app/boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform
      - volume-boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform-vendor:/app/boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform/vendor
      - volume-boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform-node_modules:/app/boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform/node_modules
    networks:
      - boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform-network
      - mysql-network
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

volumes:
 volume-boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform-vendor:
  name: volume-boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform-vendor
 volume-boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform-node_modules:
  name: volume-boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform-node_modules

networks:
   boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform-network:
    name: boilerplate-laravel-10-clean-architecture-ecr-ecs-terraform-network
    driver: bridge
   mysql-network:
    name: mysql-network
    external: true

